apiVersion: v1
kind: Service
metadata:
  name: {{ include "shar.fullname" . }}
  labels:
    {{- include "shar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: 16686
      targetPort: jaeger-query
      protocol: TCP
      name: jaeger-query
    - port: 14268
      targetPort: jaeger-thrift
      protocol: TCP
      name: jaeger-thrift
  selector:
    {{- include "shar.selectorLabels" . | nindent 4 }}
