// Code generated by mockery v2.43.1. DO NOT EDIT.

package cache

import (
	z "github.com/dgraph-io/ristretto/z"
	mock "github.com/stretchr/testify/mock"
)

// MockBackend is an autogenerated mock type for the Backend type
type MockBackend[K z.Key, V interface{}] struct {
	mock.Mock
}

type MockBackend_Expecter[K z.Key, V interface{}] struct {
	mock *mock.Mock
}

func (_m *MockBackend[K, V]) EXPECT() *MockBackend_Expecter[K, V] {
	return &MockBackend_Expecter[K, V]{mock: &_m.Mock}
}

// Get provides a mock function with given fields: key
func (_m *MockBackend[K, V]) Get(key K) (V, bool) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 V
	var r1 bool
	if rf, ok := ret.Get(0).(func(K) (V, bool)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(K) V); ok {
		r0 = rf(key)
	} else {
		r0 = ret.Get(0).(V)
	}

	if rf, ok := ret.Get(1).(func(K) bool); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Get(1).(bool)
	}

	return r0, r1
}

// MockBackend_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBackend_Get_Call[K z.Key, V interface{}] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key K
func (_e *MockBackend_Expecter[K, V]) Get(key interface{}) *MockBackend_Get_Call[K, V] {
	return &MockBackend_Get_Call[K, V]{Call: _e.mock.On("Get", key)}
}

func (_c *MockBackend_Get_Call[K, V]) Run(run func(key K)) *MockBackend_Get_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(K))
	})
	return _c
}

func (_c *MockBackend_Get_Call[K, V]) Return(_a0 V, _a1 bool) *MockBackend_Get_Call[K, V] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBackend_Get_Call[K, V]) RunAndReturn(run func(K) (V, bool)) *MockBackend_Get_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function with given fields: key, value
func (_m *MockBackend[K, V]) Set(key K, value V) bool {
	ret := _m.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(K, V) bool); ok {
		r0 = rf(key, value)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// MockBackend_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockBackend_Set_Call[K z.Key, V interface{}] struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - key K
//   - value V
func (_e *MockBackend_Expecter[K, V]) Set(key interface{}, value interface{}) *MockBackend_Set_Call[K, V] {
	return &MockBackend_Set_Call[K, V]{Call: _e.mock.On("Set", key, value)}
}

func (_c *MockBackend_Set_Call[K, V]) Run(run func(key K, value V)) *MockBackend_Set_Call[K, V] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(K), args[1].(V))
	})
	return _c
}

func (_c *MockBackend_Set_Call[K, V]) Return(_a0 bool) *MockBackend_Set_Call[K, V] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBackend_Set_Call[K, V]) RunAndReturn(run func(K, V) bool) *MockBackend_Set_Call[K, V] {
	_c.Call.Return(run)
	return _c
}

// NewMockBackend creates a new instance of MockBackend. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackend[K z.Key, V interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackend[K, V] {
	mock := &MockBackend[K, V]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
